# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
  namespace: default
  labels:
    app: redis-master
spec:
  selector:
    matchLabels:
      app: redis-master
      role: master
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: redis-master
      labels:
        app: redis-master
        role: master
    spec:
      containers:
        - name: redis-master
          image: redis:7.2
          ports:
            - containerPort: 6379
              name: redis-server # <--- not redis-master!!!
          command: ["redis-server", "--bind", "0.0.0.0", "--port", "6379"]
---

