# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: default
  labels:
    app: redis-master
    role: master
spec:
  ports:
  - name: redis-master
    port: 6379
    targetPort: redis-server
  selector:
    app: redis-master
    role: master
---

